baseURL = "https://celestine.eideon.com"
languageCode = "en-us"
title = "Cèlestine"
theme = "split"

pluralizelisttitles = "false"
enableRobotsTXT = true
canonifyURLs = true
#googleAnalytics = ""

[params]

    [params.visual.image]
        enable = false

    [params.visual.video]
        enable = true
        mute = true
        file = "videos/flowers_bloom_before_your_eyes.mp4"
        # youtubeId = "LjCzPp-MK48"

[markup.goldmark.renderer]
    unsafe= true